//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaCatalina
{
    using System;
    using System.Collections.Generic;
    
    public partial class comOrdenCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public comOrdenCompra()
        {
            this.comOrdenCompraDetalle = new HashSet<comOrdenCompraDetalle>();
        }
    
        public string codEmp { get; set; }
        public int ordenCompra_id { get; set; }
        public string codEmpRequerimiento { get; set; }
        public Nullable<int> requerimiento_id { get; set; }
        public System.DateTime fecha { get; set; }
        public string proveed_id { get; set; }
        public Nullable<int> sectorRequerimiento_id { get; set; }
        public int estado_id { get; set; }
        public int tipoOc_id { get; set; }
        public int modificaCosto { get; set; }
        public string condicionPago_id { get; set; }
        public string obs { get; set; }
        public string usuario { get; set; }
        public string usuarioAutoriza { get; set; }
        public Nullable<decimal> PDC { get; set; }
        public Nullable<System.DateTime> fechaAutorizacion { get; set; }
        public string motivoFinaliz_Anulacion { get; set; }
        public Nullable<System.DateTime> fechaFinaliz_Anulacion { get; set; }
        public Nullable<bool> pedidoDiario { get; set; }
        public string proveed_Original { get; set; }
        public Nullable<int> sectorEntrega_id { get; set; }
        public Nullable<short> tipoProrrateo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comOrdenCompraDetalle> comOrdenCompraDetalle { get; set; }
    }
}
