//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaCatalina
{
    using System;
    using System.Collections.Generic;
    
    public partial class comOrdenCompraDetalle
    {
        public string codEmp { get; set; }
        public int ordenCompra_id { get; set; }
        public int nroItem { get; set; }
        public int nivelAuto_id { get; set; }
        public double importe { get; set; }
        public string detalle { get; set; }
        public Nullable<decimal> cantidad { get; set; }
    
        public virtual comOrdenCompra comOrdenCompra { get; set; }
    }
}
