//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaCatalina
{
    using System;
    using System.Collections.Generic;
    
    public partial class comRequerimientoInternoItem
    {
        public string codEmp { get; set; }
        public int requerimiento_id { get; set; }
        public int nroItem { get; set; }
        public string articulo_id { get; set; }
        public string uniMed { get; set; }
        public decimal cantidad { get; set; }
        public int nivelAut_id { get; set; }
        public System.DateTime fechaEntrega { get; set; }
        public string marca { get; set; }
        public Nullable<int> excluido { get; set; }
        public string motivoExclusion { get; set; }
        public string usuarioExcluye { get; set; }
    
        public virtual comRequerimientoInterno comRequerimientoInterno { get; set; }
    }
}
