//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaCatalina
{
    using System;
    using System.Collections.Generic;
    
    public partial class comRequerimientoInterno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public comRequerimientoInterno()
        {
            this.comRequerimientoInternoItem = new HashSet<comRequerimientoInternoItem>();
        }
    
        public string codEmp { get; set; }
        public int requerimiento_id { get; set; }
        public System.DateTime fecha { get; set; }
        public int sectorRequerimiento_id { get; set; }
        public int estado_id { get; set; }
        public string obs { get; set; }
        public string usuario { get; set; }
        public string usuarioAutoriza { get; set; }
        public Nullable<System.DateTime> fechaAutorizacion { get; set; }
        public string motivoAnulacion { get; set; }
        public Nullable<bool> pedidoDiario { get; set; }
        public Nullable<int> sectorEntrega_id { get; set; }
        public Nullable<System.DateTime> fechaFinalizacion { get; set; }
        public string motivoFinalizacion { get; set; }
        public string usuarioFinaliza { get; set; }
        public Nullable<int> depositoOrigen_id { get; set; }
        public Nullable<int> sectorDepositoOrigen_id { get; set; }
        public Nullable<int> depositoDestino_id { get; set; }
        public Nullable<int> sectorDepositoDestino_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comRequerimientoInternoItem> comRequerimientoInternoItem { get; set; }
    }
}
