//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaCatalina
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SBDARSCEntities : DbContext
    {
        public SBDARSCEntities()
            : base("name=SBDARSCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<USR_ArticuloSubCuenta> USR_ArticuloSubCuenta { get; set; }
        public virtual DbSet<USR_ConceptoSubCuenta> USR_ConceptoSubCuenta { get; set; }
        public virtual DbSet<USR_ControlProrrateoEmpresa> USR_ControlProrrateoEmpresa { get; set; }
    
        public virtual ObjectResult<TraeConceptoCtaContable_Result> TraeConceptoCtaContable()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TraeConceptoCtaContable_Result>("TraeConceptoCtaContable");
        }
    }
}
