//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaCatalina
{
    using System;
    using System.Collections.Generic;
    
    public partial class stkMoviReqInterno
    {
        public string codEmpStk { get; set; }
        public int comprobanteStk { get; set; }
        public int nroItemStk { get; set; }
        public string codEmp { get; set; }
        public int requerimiento_id { get; set; }
        public int nroItem { get; set; }
        public string uniMed { get; set; }
        public decimal cantEnviada { get; set; }
        public string remSucursal { get; set; }
        public int remComprobante { get; set; }
    }
}
