//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaCatalina
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Usuarios()
        {
            this.comUsuarioEnviaMail = new HashSet<comUsuarioEnviaMail>();
        }
    
        public int Id_Usuario { get; set; }
        public int Id_Perfil { get; set; }
        public string IdentificadorUsuario { get; set; }
        public string ContraseniaUsuario { get; set; }
        public string NombreUsuario { get; set; }
        public bool Inactivo { get; set; }
        public Nullable<int> Sector_id { get; set; }
        public string Email { get; set; }
        public string Empresa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comUsuarioEnviaMail> comUsuarioEnviaMail { get; set; }
    }
}
