'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class comOrdenCompra
    Public Property codEmp As String
    Public Property ordenCompra_id As Integer
    Public Property codEmpRequerimiento As String
    Public Property requerimiento_id As Nullable(Of Integer)
    Public Property fecha As Date
    Public Property proveed_id As String
    Public Property sectorRequerimiento_id As Nullable(Of Integer)
    Public Property estado_id As Integer
    Public Property tipoOc_id As Integer
    Public Property modificaCosto As Integer
    Public Property condicionPago_id As String
    Public Property obs As String
    Public Property usuario As String
    Public Property usuarioAutoriza As String
    Public Property PDC As Nullable(Of Decimal)
    Public Property fechaAutorizacion As Nullable(Of Date)
    Public Property motivoFinaliz_Anulacion As String
    Public Property fechaFinaliz_Anulacion As Nullable(Of Date)
    Public Property pedidoDiario As Nullable(Of Boolean)
    Public Property proveed_Original As String
    Public Property sectorEntrega_id As Nullable(Of Integer)
    Public Property tipoProrrateo As Nullable(Of Short)

    Public Overridable Property comOrdenCompraDetalle As ICollection(Of comOrdenCompraDetalle) = New HashSet(Of comOrdenCompraDetalle)

End Class
