'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class comOrdenCompraDetalle
    Public Property codEmp As String
    Public Property ordenCompra_id As Integer
    Public Property nroItem As Integer
    Public Property nivelAuto_id As Integer
    Public Property importe As Double
    Public Property detalle As String
    Public Property cantidad As Nullable(Of Decimal)

    Public Overridable Property comOrdenCompra As comOrdenCompra

End Class
