'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class BLLEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=BLLEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property stkMoviReqInterno() As DbSet(Of stkMoviReqInterno)
    Public Overridable Property comOrdenCompra() As DbSet(Of comOrdenCompra)
    Public Overridable Property comOrdenCompraDetalle() As DbSet(Of comOrdenCompraDetalle)

    Public Overridable Function ExisteItemMoviReqInterno(codEmp As String, requerimiento_id As Nullable(Of Integer), nroItem As Nullable(Of Integer)) As ObjectResult(Of ExisteItemMoviReqInterno_Result)
        Dim codEmpParameter As ObjectParameter = If(codEmp IsNot Nothing, New ObjectParameter("codEmp", codEmp), New ObjectParameter("codEmp", GetType(String)))

        Dim requerimiento_idParameter As ObjectParameter = If(requerimiento_id.HasValue, New ObjectParameter("requerimiento_id", requerimiento_id), New ObjectParameter("requerimiento_id", GetType(Integer)))

        Dim nroItemParameter As ObjectParameter = If(nroItem.HasValue, New ObjectParameter("nroItem", nroItem), New ObjectParameter("nroItem", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of ExisteItemMoviReqInterno_Result)("ExisteItemMoviReqInterno", codEmpParameter, requerimiento_idParameter, nroItemParameter)
    End Function

End Class
