'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class stkMoviReqInterno
    Public Property codEmpStk As String
    Public Property comprobanteStk As Integer
    Public Property nroItemStk As Integer
    Public Property codEmp As String
    Public Property requerimiento_id As Integer
    Public Property nroItem As Integer
    Public Property uniMed As String
    Public Property cantEnviada As Decimal
    Public Property remSucursal As String
    Public Property remComprobante As Integer

End Class
